Add divider to side menu
check-the-weather/check-the-weather pull request #17
Opened 2021-09-17 05:34 UTC by callumgedling

**Description**

Added a divider to the side menu

**Testing**

Testing done on local host to see changes.

**Extra Attention**

N/A

2021-09-17 05:42 UTC, connorKeir approved these changes

2021-09-17 07:01 UTC, jonachehilton requested changes
Firstly, change the class name to something like `Divider` and then See if this works:

```
width: 100%;
height: 2px;
margin: 15px 0px;
background-color: #727272;
```

2021-09-23 01:28 UTC, jonachehilton commented on client/src/components/Sidebar.module.css
> +
Line 51: Add space between .Divider and {

Line 52: Remove empty line

2021-09-23 04:10 UTC, jonachehilton approved these changes

2021-09-23 04:11 UTC, merged