Beginning of the Titleheader
check-the-weather/check-the-weather pull request #18
Opened 2021-09-17 12:40 UTC by connorKeir

**Description**

Starter work on Titleheader

**Testing**

Attempted putting in component in Overview page to see how it worked. the page title looked fine. Name was too far down

**Extra Attention**

Need advice on how to position Name. Also should I be exporting the getName function to this component to make it easier to use? Especially with trying to get last name.

2021-09-17 13:55 UTC, jonachehilton requested changes
Great first crack at it.

You shouldn't need to pass the getName function anywhere. The `name` useState variable is already passed into the overview prop so you can just pass it into the TitleHeader prop from there.

However, you should change the getName function on line 15 so that it sets the name state to have both the first and last name. It should look something like this:
```
setName(`${response.firstName} ${response.lastName}`)
```

2021-09-17 13:55 UTC, jonachehilton commented on package-lock.json
> +  "packages": {
I'm not sure what you did, but you somehow added 5000 lines to this file. That should not have happened. Please revert it back

2021-09-17 13:55 UTC, jonachehilton commented on package-lock.json
> +  "packages": {
Similarly with the `client/package-lock.json`, 21000 lines changed

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +function Titleheader({name}){
Generally, React components should be named with a capital letter for each word. So the function name, file name and class name should be `TitleHeader`.

It's also good practice to add padding spaces whenever you define an object or your destructuring an object. So line 4 should look like this `function TitleHeader({ name }) {`. Note that there is also a space between ) and {. Similarly there should be a space between return and the open bracket on line 5. Linting should be setup so if you run the linter it will tell you all these types of errors that you are doing. To run it do `cd client` and then `npm run lint`.

When we call the internal API to fetch the name from the database, it will return a firstName and a lastName. One options is to pass first and lastname in as props or we can use your current implimentation with just `name` and concatenate the 2 names before you pass it into the component - your choice.

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +    <div className={styles.Overview}>
Generally if the outermost element of your component takes in a style that style name should be the same as the component name. So instead of Overview it would be `TitleHeader`

Lines 6-13 inclusive need to be indented.

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +            <h1>Overview</h1>
Because we want this component to be reusable for every page, the actual title string should be a prop that is passed in.
So line 8 would look like:
```
<h1>{title}</h1>
```

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.module.css
> +  flex-direction: column;
You almost got the styling right. 

Flex direction should be row instead of collumn and you shoudn't need to give a height as it's automatically done here.

Should look like this:
```
  display: flex;
  flex-direction: row;
  width: 100%;
```

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.module.css
> +  display: flex;
Almost there.

Just need a left margin so that it does not hug the left hand of the screen

Should look like this:
```
  display: flex;
  justify-content: flex-start;
  margin-left: 25px;
  width: 100%;
```

2021-09-17 13:55 UTC, jonachehilton commented on client/src/components/Titleheader.module.css
> +  height: 50000%;
Should never use a percentage that is more than 100%. And percentage is not always what you want. Most of the time you will want to use pixels.

Just need to add a right margin so that it does not hug the right hand of the screen.

This is what it should look like:

```
  display: flex;
  justify-content: flex-end;
  margin-right: 25px;
  width: 100%;
```

2021-09-18 01:53 UTC, connorKeir commented on package-lock.json
> +  "packages": {
@jonachehilton never opened either of these files anything else I could have been doing this? Can't revert it with ctrl Z and have no clue what to do to fix it.

2021-09-18 02:00 UTC, jonachehilton commented on package-lock.json
> +  "packages": {
Just delete the contents of file and copy and paste the contents of original file

https://github.com/check-the-weather/check-the-weather/blob/develop/package-lock.json

https://github.com/check-the-weather/check-the-weather/blob/develop/client/package-lock.json

2021-09-18 02:09 UTC, connorKeir commented on package-lock.json
> +  "packages": {
awesome, glad thats an easy fix. Still weird that it happened. Wonder if its one of the commands in the git bash?

2021-09-18 02:19 UTC, connorKeir commented on client/src/components/Titleheader.module.css
> +  height: 50000%;
ahhh yeah righto and Im guessing the fact that I had the .TitleHeader as a column and not a row was what was causing it too look funny, not a matter of height. Cheers Joni

2021-09-20 00:45 UTC, jonachehilton reviewed
Can you please resolve the conversations on the PR that have been addressed, that way I know what you have addressed and can double check it. If there is a conversation that you have not addressed, need hep with, or disagree with you can leave it open.


I only had a quick look cause I'm at work. This should be enough to get you going again. I will do a more comprehensive review when I finish work.

2021-09-20 00:45 UTC, jonachehilton commented on server/routes/dashboard.js
>      const user = await pool.query('SELECT first_name FROM users WHERE user_id = $1', [req.user]);
The reason why last name is not propagating through the the frontend is here. Needs to select last_name as well

2021-09-20 00:45 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +        const profileImage = await wretch('https://avatars.dicebear.com/api/micah/'+ name +'.svg').get().json()
I don't think functional components can be asynchronous and thats probably why it's giving you an error.

Typically you would put this type of thing in an async function  inside the functional component and then call it in a React useEffect hook with profileImage as state (using useState).  Look at lines 9-27 of Overview.js.

2021-09-20 00:48 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +        const profileImage = await wretch('https://avatars.dicebear.com/api/micah/'+ name +'.svg').get().json()
Also, you should be using string interpolation for the URL. https://www.w3schools.com/js/js_string_templates.asp

2021-09-21 05:47 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +                <img src={profileImage} alt="User profile"></img>
I forgot that there is a much easier way to do this. You can get delete lines 7 to 18.

Just do this instead:
```
<img src={`https://avatars.dicebear.com/api/micah/${name}.svg`} alt="User profile"></img>
```

Only other thing to do is to give it a style with an appropriate width and height.

2021-09-21 10:11 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +import React, { useEffect, useState } from 'react'
Remove react hooks

2021-09-21 10:13 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +import React, { useEffect, useState } from 'react'
Also the name of this file is still `Titleheader.js`, it should match the component name `TitleHeader.js`

2021-09-21 10:19 UTC, jonachehilton commented on client/src/components/Titleheader.js
> +import React, { useEffect, useState } from 'react'
Same with the css file name

2021-09-21 13:08 UTC, connorKeir commented on client/src/Pages/Dashboard/Dashboard.js
> +      console.log(response)
Not see this on my version.

2021-09-21 13:19 UTC, connorKeir commented on client/src/components/Titleheader.js
> +import React, { useEffect, useState } from 'react'
np, I changed it with the classic right click initially and not the git mv command

2021-09-22 13:05 UTC, connorKeir commented
Let me know any style changes you want. Have aligned the items so they should be on the same bottom. Not sure if I like it. Also added a divider, as it was in figma. Unsure how good it looks. Let me know what needs to be change otherwise merge?

2021-09-23 01:33 UTC, jonachehilton commented on client/src/Pages/Dashboard/Overview.js
>            <h1>{name}'s Overview</h1>
Not removed yet

2021-09-23 01:33 UTC, jonachehilton commented on client/src/components/TitleHeader.js
> +
Should be only one space between imports and function declaration

2021-09-23 04:12 UTC, connorKeir commented on client/src/Pages/Dashboard/Overview.js
>            <h1>{name}'s Overview</h1>
I think it didn't commit for some reason , Will make sure that it gets put in next push.

2021-09-25 04:11 UTC, closed without merging